document.write("<table>");                                                      
document.write("<tr>");                                                         
document.write("<caption>Wait class over day</caption>");                       
document.write("<thead>");                                                      
document.write("<th>WaitClass/Hour</th>");                                      
document.write("<th>0</th>");                                                   
document.write("<th>1</th>");                                                   
document.write("<th>2</th>");                                                   
document.write("<th>3</th>");                                                   
document.write("<th>4</th>");                                                   
document.write("<th>5</th>");                                                   
document.write("<th>6</th>");                                                   
document.write("<th>7</th>");                                                   
document.write("<th>8</th>");                                                   
document.write("<th>9</th>");                                                   
document.write("<th>10</th>");                                                  
document.write("<th>11</th>");                                                  
document.write("<th>12</th>");                                                  
document.write("<th>13</th>");                                                  
document.write("<th>14</th>");                                                  
document.write("<th>15</th>");                                                  
document.write("<th>16</th>");                                                  
document.write("<th>17</th>");                                                  
document.write("<th>18</th>");                                                  
document.write("<th>19</th>");                                                  
document.write("<th>20</th>");                                                  
document.write("<th>21</th>");                                                  
document.write("<th>22</th>");                                                  
document.write("<th>23</th>");                                                  
document.write("</tr>");                                                        
document.write("</thead>");                                                     
document.write("<tbody>");                                                      
document.write("<tr>");                                                         
document.write("<tr>")                                                          
document.write("<th>Concurrency</th>")                                          
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>User I/O</th>")                                             
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>System I/O</th>")                                           
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Administrative</th>")                                       
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Other</th>")                                                
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Configuration</th>")                                        
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Scheduler</th>")                                            
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Cluster</th>")                                              
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Application</th>")                                          
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Network</th>")                                              
document.write("</tr>")                                                         
document.write("<tr>")                                                          
document.write("<th>Commit</th>")                                               
document.write("</tr>")                                                         
document.write("</tbody>");                                                     
document.write("</table>");                                                     
